version: '2'
services:
    datascience-notebook:
        image: freqtradeorg/freqtrade:stable
        volumes:
            - "./user_data:/freqtrade/user_data"     
        ports:
            - 8891:8888
        command: "start-notebook.sh"
        user: root
        environment:
          NB_USER: docker_worker
          NB_UID: 1008
          NB_GID: 1011
          CHOWN_HOME: 'yes'
          CHOWN_HOME_OPTS: -R