---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:80:80"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile user_data/logs/freqtrad.log
      --db-url sqlite:////user_data/tradesv2.sqlite
      --config user_data/config.json
      --strategy Saturn5
