---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade-docker-strategy/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:80:80"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade-docker-strategy/user_data/logs/freqtradi.log
      --db-url sqlite:////freqtrade-docker-strategy/user_data/tradesv3.sqlite
      --config /freqtrade-docker-strategy/user_data/config.json
      --strategy Saturn5
